// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbX0JAyk41QIbyFSfQrVmm8DeZVffBpns',
    appId: '1:890068535217:android:10737f13221e5d742c9f90',
    messagingSenderId: '890068535217',
    projectId: 'fretfly-67cb0',
    storageBucket: 'fretfly-67cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpgHRmUXozvQTgBpKS7eSNWbwV8BKted4',
    appId: '1:890068535217:ios:75ce4f11291590742c9f90',
    messagingSenderId: '890068535217',
    projectId: 'fretfly-67cb0',
    storageBucket: 'fretfly-67cb0.firebasestorage.app',
    iosBundleId: 'com.fluttermapp.fretfly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpgHRmUXozvQTgBpKS7eSNWbwV8BKted4',
    appId: '1:890068535217:ios:75ce4f11291590742c9f90',
    messagingSenderId: '890068535217',
    projectId: 'fretfly-67cb0',
    storageBucket: 'fretfly-67cb0.firebasestorage.app',
    iosBundleId: 'com.fluttermapp.fretfly',
  );
}
